name: example
description: Example of the Fluttery package.

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.0

dev_dependencies:
  fluttery:
    path: ../
  flutter_test:
    sdk: flutter


# The following section is specific to Flutter.
flutter:
  uses-material-design: true
